# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_auto_20220718_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_by',
            field=models.CharField(choices=[('manual', 'manual'), ('facebook', 'facebook'), ('google', 'google'), ('apple', 'apple')], max_length=10),
        ),
    ]
